version: '3'
services:
  db:
    container_name: 'mysql'
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
    env_file:
      - 'docker/mysql.env'
    ports:
      - '3307:3306'
    command:
      - '--innodb_use_native_aio=0'
    volumes:
      - './docker/database/data:/var/lib/mysql'
    restart: unless-stopped

  rails:
    container_name: 'app'
    build: "docker/rails"
    ports: 
      - '3000:3000'
    volumes: 
      - './demo:/usr/src/app'
    working_dir: '/usr/src/app'
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -p 3000 -b '0.0.0.0'"